ALTER TABLE users ADD COLUMN deleted_at TIMESTAMPTZ DEFAULT NULL;

ALTER TABLE attachments ALTER COLUMN message_id DROP NOT NULL;
ALTER TABLE attachments ADD COLUMN uploaded_by UUID REFERENCES users(user_id) ON DELETE SET NULL;
